"""Add is_enabled, description

Revision ID: 66f35e04a00b
Revises: d6154b9f35ca
Create Date: 2025-12-19 22:51:29.975308+00:00

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "66f35e04a00b"
down_revision = "d6154b9f35ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_form", sa.Column("description", sa.String(length=256), nullable=True))
    op.add_column("user_form", sa.Column("is_enabled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_form", "is_enabled")
    op.drop_column("user_form", "description")
    # ### end Alembic commands ###
