"""change id to UUID

Revision ID: 359a07c8cc6f
Revises: 71edd3a85c9c
Create Date: 2025-12-09 09:12:11.152837+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "359a07c8cc6f"
down_revision = "71edd3a85c9c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE user_form ALTER COLUMN id DROP DEFAULT")

    op.alter_column(
        "user_form",
        "id",
        existing_type=sa.INTEGER(),
        type_=postgresql.UUID(as_uuid=True),
        existing_nullable=False,
        postgresql_using="(md5(id::text))::uuid",
    )

    op.execute("DROP SEQUENCE IF EXISTS user_form_id_seq")

    op.drop_index(op.f("ix_user_form_id"), table_name="user_form")
    op.drop_constraint(op.f("user_form_user_id_fkey"), "user_form", type_="foreignkey")
    op.create_foreign_key(
        None,
        "user_form",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_form", type_="foreignkey")
    op.create_foreign_key(op.f("user_form_user_id_fkey"), "user_form", "users", ["user_id"], ["id"])
    op.create_index(op.f("ix_user_form_id"), "user_form", ["id"], unique=True)
    op.alter_column("user_form", "id", existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=False)
    # ### end Alembic commands ###
