"""add qrcode

Revision ID: d6154b9f35ca
Revises: 359a07c8cc6f
Create Date: 2025-12-11 13:10:51.396536+00:00

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d6154b9f35ca"
down_revision = "359a07c8cc6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_form", sa.Column("qrcode", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_form", "qrcode")
    # ### end Alembic commands ###
