"""Add Comment model.

Revision ID: 950bf2ee8ce9
Revises: 66f35e04a00b
Create Date: 2025-12-21 15:39:37.760406+00:00

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "950bf2ee8ce9"
down_revision = "66f35e04a00b"
branch_labels = None
depends_on = None
"""Add Comment model.

Revision ID: 950bf2ee8ce9
Revises: 66f35e04a00b
Create Date: 2025-12-21 15:39:37.760406+00:00

"""


# revision identifiers, used by Alembic.
revision = "950bf2ee8ce9"
down_revision = "66f35e04a00b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("first_name", sa.String(length=32), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("phone", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("user_form_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_form_id"], ["user_form.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_user_form_id"), "comments", ["user_form_id"], unique=False)
    op.drop_index(op.f("ix_user_form_user_id"), table_name="user_form")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_user_form_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_user_forms_user_id"), table_name="private_page")
    op.drop_table("private_page")
    # ### end Alembic commands ###
