"""add user_form

Revision ID: 71edd3a85c9c
Revises: 460ec7cf8bbf
Create Date: 2025-11-21 12:37:44.457368+00:00

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "71edd3a85c9c"
down_revision = "460ec7cf8bbf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_form",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_form_id"), "user_form", ["id"], unique=True)
    op.create_index(op.f("ix_user_form_user_id"), "user_form", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_form_user_id"), table_name="user_form")
    op.drop_index(op.f("ix_user_form_id"), table_name="user_form")
    op.drop_table("user_form")
    # ### end Alembic commands ###
