"""In auth add avatar_key

Revision ID: a1fb10af1d4e
Revises: 459ebeaa310c
Create Date: 2026-03-04 11:12:13.948936+00:00

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a1fb10af1d4e'
down_revision = '459ebeaa310c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_key', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('uq_users_usercode'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_usercode'), 'users', ['usercode'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'avatar_key')
    # ### end Alembic commands ###
