"""autogenerated_migration

Revision ID: 459ebeaa310c
Revises: 80dfe94fb85f
Create Date: 2026-02-14 15:02:14.692131+00:00

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '459ebeaa310c'
down_revision = '80dfe94fb85f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usercode', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usercode')
    # ### end Alembic commands ###
