"""Added tg_accounts for users integrations_tests

Revision ID: 0bb0912895d2
Revises: 950bf2ee8ce9
Create Date: 2026-01-12 18:59:27.806527+00:00

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0bb0912895d2"
down_revision = "950bf2ee8ce9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_user_form_user_id"), "user_form", ["user_id"], unique=False)
    op.add_column("users", sa.Column("tg_account", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tg_account")
    op.drop_index(op.f("ix_user_form_user_id"), table_name="user_form")
    # ### end Alembic commands ###
