"""return notify_email_enabled

Revision ID: 80dfe94fb85f
Revises: b90ebe183a12
Create Date: 2026-02-03 15:32:42.515934+00:00

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "80dfe94fb85f"
down_revision = "b90ebe183a12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "notify_email_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("users", "notify_email_enabled", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notify_email_enabled")
    # ### end Alembic commands ###
