"""change notify_email

Revision ID: b90ebe183a12
Revises: 50ba6c9afce7
Create Date: 2026-02-03 15:29:54.934055+00:00

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b90ebe183a12"
down_revision = "50ba6c9afce7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("notify_email", sa.String(length=255), nullable=True))
    op.drop_column("users", "notify_email_enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("notify_email_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("users", "notify_email")
    # ### end Alembic commands ###
