name: Build Image

on:
  workflow_dispatch:
  push:
    branches: [ main, test, dev ]

env:
  DEV_IMAGE_TAG: latest
  TEST_IMAGE_TAG: rc
  MAIN_IMAGE_TAG: stable

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Get image repository path
        shell: bash
        run: echo "IMAGE_REPO=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Get timestamp
        shell: bash
        run: echo "TIMESTAMP_TAG=$(date -u +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Set branch tag
        uses: iamtheyammer/branch-env-vars@v1.2.2
        with:
          IMAGE_TAG: |
            main:${{ env.MAIN_IMAGE_TAG }}
            test:${{ env.TEST_IMAGE_TAG }}
            dev:${{ env.DEV_IMAGE_TAG }}

      - name: Build image
        uses: QliqyService/deployment/.github/actions/build@main
        with:
          image: ${{ env.IMAGE_REPO }}
          image-tag: ${{ env.IMAGE_TAG }}
          commit-tag: ${{ github.sha }}
          image-timestamp-tag: ${{ env.TIMESTAMP_TAG }}-${{ env.IMAGE_TAG }}
          context: .
          dockerfile: .deployment/Dockerfile
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            APP_RELEASE=${{ env.TIMESTAMP_TAG }}-${{ env.IMAGE_TAG }}